Refactor: 액티비티 파트를 리팩토링 진행
projects-workshop/walkerholic pull request #2
Opened 2021-12-22 17:07 UTC by yunhalee05

이전 comment를 확인하고 코드를 변경하였습니다!

✔️ activityRequest와 activity에 builder를 이용하여 생성자가 중복되는 것을 방지하였습니다.
✔️ activityServiceTests에서는 builder를 사용하여 테스트를 진행하고 uploadImage테스트 코드를 추가로 작성하였습니다. 
✔️ activity create시에는 이미지 url을 디폴트 이미지로 설정하도록 하고 이미지 업로드가 필요한 경우에만 "activities/{id}/images"경로를 통하여 이미지 업로드및 이미지 url 업데이트가 가능하도록 하였습니다. 
✔️ 이때, 기존 이미지 삭제메서드는 기존 이미지가 디폴트 이미지와 경로가 동일하지 않을 때만 파일을 삭제하도록 하였습니다. 

그런데 혹시 create와 update 메서드를 uploadImage메서드와 분리하였을때, 각각의 메서드가 서로 다른 트랜잭션에서 이뤄지고있는데 하나의 액티비티를 대상으로 하는 create(create+uploadImage) 혹은  update(update + uploadImage) 기능들이 다른 트랜잭션에서 일어나도 괜찮은 걸까요? 😭

2021-12-26 17:22 UTC, brainbackdoor requested changes
음.. 반드시 activity 정보와 file을 한번에 보내야 하나요?
이미지를 업로드한 후 성공하면 url을 반환받고, 이를 activity request 에 담아도 되지않을까요?
그럼 이미지 업로드가 실패하면 activity 생성시엔 default 이미지를, 수정은 실패가 진행될거구요.
현재, uploadImage에서 activity update 도 이루어지고 있는데, 이미지 업로드 역할만 맡기는 것은 어떨까요

2021-12-29 09:58 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +    }
이미지 업로드 로직은 이미지 업로드 기능만을 담당하도록 변경하고 액티비티 생성시에 imageUrl이 없다면 default이미지로 저장하도록 변경하였습니다! 
원래 이미지를 제거하는 로직은 s3ImageUploader로 옮겨 관심사에 맞게 위치하도록 변경하였습니다!

2021-12-29 10:01 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse activityResponse = activityService.create(activityRequest);
@BeforeEach 테스트 텍스처를 만들어 중복되는 부분을 리팩토링 하였습니다!
이미지 업로드 기능을 테스트 할 경우 불필요한 다른 시나리오 테스트가 진행되지 않도록 업로드이미지 메서드는 업로드의 기능만을 담당하도록  변경하였습니다!

2021-12-31 15:39 UTC, brainbackdoor approved these changes
피드백 반영 잘해주셨네요~ 👍🏻 
몇가지 피드백 남겨두었어요~ 확인해보셔요~ 
올 한해도 고생 많으셨어요~

2021-12-31 15:39 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +                defaultImageUrl : activityRequest.getImageUrl());
음.. defaultImageUrl 을 상수로 관리하고 이미지 URL에 대한 책임을 activity 에 위임하는 것은 어떨까요?

2021-12-31 15:39 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +    }
BeforeEach을 활용해서 중복코드를 제거하신 것은 좋습니다.
다만, BeforeEach에 두면 사용하지 않는 테스트에서도 이를 수행하는 경우가 생길 수 있어요.
현재는 activityRequest 하나이지만, 테스트 케이스가 많아지면 다양한 경우가 생기겠죠. 그만큼 결합도 높아질테구요.
Fixture를 만들라는 것이 BeforeEach를 만들라는 의미는 아니었어요.
이 역시 메서드를 작은 단위들로 쪼개서 재사용하라는 의미였어요. 
혹시 이해가 잘 되지 않는다면, 다음 데일리 때 예시를 보여드릴게요~

2021-12-31 15:39 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/dto/ActivityRequest.java
> +        @NonNull String description, String imageUrl) {
NonNull annotation 을 활용했군요! 👍🏻 
저는 롬복을 선호하지 않아서.. ㅎㅎ

2022-01-01 12:32 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/service/ActivityService.java
> +                defaultImageUrl : activityRequest.getImageUrl());
확인하여 activity 속성인 이미지 URL책임을 activity가 수행할 수 있도록 DEFUALT_IMAGE_URL을 상수로 지정하여 이미지를 변경할 수 있도록 바꾸었습니다!

2022-01-01 12:33 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +    }
해당부분 확인하여 단위테스트에서 사용하지 않는 부분도 반복적으로 불필요하게 setUp하지 않도록 setUp()메소드를 만들고 이를 필요에 따라서만 사용이 가능하도록 변경하였습니다!

2022-01-01 12:39 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/activity/dto/ActivityRequest.java
> +        @NonNull String description, String imageUrl) {
확인하였습니다! 😃 이 부분은 생성자 중복 생성코드를 막기 위해서 롬복의 @Builder를 사용하게 되었는데 혹시 롬복의 @Builder를 사용하지 않는다면 빌더패턴을 이용해서 Builder를 구현하는 것은 괜찮을까요?

2022-01-03 01:27 UTC, brainbackdoor approved these changes
제 피드백을 그대로 수용하시지 않아도 괜찮아요.
리뷰는 저의 의견일 뿐이니, 윤하님 의견을 적극적으로 표현해주시면 좋을거 같아요. ㅎㅎ
이 PR 은 오래되었으니, 여기서 merge 하고 다음 작업 진행하는게 좋을듯합니다.

2022-01-03 01:27 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/activity/dto/ActivityRequest.java
> +        @NonNull String description, String imageUrl) {
아, JSR 303 혹은 380 Bean valiadtion을 활용하면 어떨까 싶었어요.
그대로 두셔도 괜찮습니다.

2022-01-03 09:27 UTC, merged