Refactor: userActivity 파트를 리팩토링 진행
projects-workshop/walkerholic pull request #3
Opened 2022-01-05 11:30 UTC by yunhalee05

userActivity 파트와 userActivity 테스트 부분을 리팩토링 진행하였습니다!

2022-01-06 18:29 UTC, brainbackdoor requested changes
전반적으로 잘 작성해주셨어요~
몇가지 피드백 남겨두었는데 확인 부탁해요~

2022-01-06 18:29 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/controller/UserActivityController.java
> +    public ResponseEntity<?> userActivities(@RequestParam("page") String page,
와일드카드를 쓰는 것보단 타입체크를 하여 문제시, 컴파일시점에서 체크하는 것은 어떨까요?

2022-01-06 18:29 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/domain/UserActivity.java
> +        }
메서드로 분리하여 메서드명으로 의도를 드러내는 건 어떨까요

2022-01-06 18:29 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/dto/UserActivityListResponse.java
> +public class UserActivityListResponse {
List, Set 등 자료구조를 지칭하는 단어를 클래스나 변수이름으로 사용하는 것을 지양하고 있습니다.
사용하는 자료구조가 변경되면 변경의 범위가 외부로 전파될 수 있기 때문입니다.
List와 같은 복수의 데이터의 경우 복수형을 쓰는 것이 더 적합하다고 생각합니다.

https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20의미%20있는%20이름.md#그릇된-정보를-피하라

2022-01-06 18:29 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +    public static final int USER_ACTIVITY_PER_PAGE = 10;
method 내 순서에 대해서도 한번 고민해보셔요.

https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2022-01-06 18:29 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/domain/ActivityRepositoryTests.java
> +            .imageUrl("testImageUrl").build();
값을 직접 바인딩하면, 다른 케이스를 테스트하기 어렵지 않을까요?

2022-01-06 18:29 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/service/UserActivityServiceTests.java
> +        userActivityResponse = userActivityService.create(userActivityRequest);
save 할 경우 반복적으로 테스트할 때 문제가 발생하진 않던가요?

2022-01-06 18:29 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +        Pageable pageable = PageRequest.of(0, USER_ACTIVITY_PER_PAGE);
pageable을 그냥 전달하면 limit offset 쿼리가 발생합니다.
이 경우 쿼리가 비효율적입니다.
가령 `SELECT * FROM a LIMIT 2000, 10;` 일 경우
2000부터 10개 row를 읽는 것이 아니라,
2000라인까지 읽은 후 버리고 10개 row를 읽습니다.

그러므로 아래와 같이 쿼리가 작성되어야 합니다.

```mysql
SELECT * FROM a
    WHERE a.id >= 2000
        ORDER BY id LIMIT 0, 10;
```

Spring Data JPQL은 LIMIT 명령어를 지원하지 않으므로, Pageable 객체를 활용해 아래와 같이 작성해야 합니다.

```java
@Query("SELECT * FROM a WHERE a.id >= ?1")
List<User> findAll(Pageable pg);
```

2022-01-06 18:29 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/service/UserActivityServiceTests.java
> +        userActivityResponse = userActivityService.create(userActivityRequest);
service test 의 목적이 무엇일까요?
통합테스트나 인수테스트는 별도로 작성하지 않나요? slice test는 없어도 괜찮지만, 인수테스트와 단위테스트는 필수라고 생각해요.

2022-01-08 10:56 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/controller/UserActivityController.java
> +    public ResponseEntity<?> userActivities(@RequestParam("page") String page,
해당 부분 확인하고 타입을 명시하여 컴파일 시점에 체크할 수 있도록 변경하였습니다!

2022-01-08 10:56 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/domain/UserActivity.java
> +        }
updateLevel()메서드로 분리하여 의도를 나타내도록 변경하였습니다!

2022-01-08 10:57 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/dto/UserActivityListResponse.java
> +public class UserActivityListResponse {
해당 부분 확인하여 UserActivityResponses로 수정하였습니다!

2022-01-08 11:01 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +    public static final int USER_ACTIVITY_PER_PAGE = 10;
해당부분 확인하고 클래스 (정적) 변수 -> 인스턴스 변수 -> 생성자 -> public method -> private method 의 순으로 위치하도록 변경하였습니다!

2022-01-08 11:01 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/domain/ActivityRepositoryTests.java
> +            .imageUrl("testImageUrl").build();
해당부분 확인하여 ParameterizedTest를 이용하여 케이스를 테스트하도록 변경하였습니다!

2022-01-08 11:05 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/service/UserActivityServiceTests.java
> +        userActivityResponse = userActivityService.create(userActivityRequest);
헤당부분을 확인하고 service 테스트시 repository에 의존하여 테스트가 이루어지는 부분을 수정하기 위해 테스트하고자 하는 객체를 InjectsMocks 어노테이션으로 표시하고 그 외의 다른 객체는 MockBean으로 등록하여 의존관계를 맺지 않도록 설정하여 서비스 계층의 단위테스트가 독립적으로 진행될 수 있도록 수정하였습니다!

2022-01-08 11:09 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +        Pageable pageable = PageRequest.of(0, USER_ACTIVITY_PER_PAGE);
이 부분은 leftJoin을 하고 있어 카운트쿼리를 작성하여 
Query(value = "SELECT DISTINCT a FROM UserActivity a LEFT JOIN FETCH a.user u WHERE u.id=:id ORDER BY a.createdAt DESC", countQuery = "SELECT count(DISTINCT a) FROM UserActivity a") 
이러한 방식으로 데이터를 불러오고 있습니다! 

혹시 여기에서 offset 쿼리를 방지하기 위해서는 
Query(value = "SELECT DISTINCT a FROM UserActivity a LEFT JOIN FETCH a.user u WHERE u.id=:id AND a.id >= ?1 ORDER BY a.createdAt DESC", countQuery = "SELECT count(DISTINCT a) FROM UserActivity a") 
  Page<UserActivity> findByUserId(Pageable pageable, Integer id);
이러한 방식으로 작성하면 되는 것일까요? 😭

2022-01-09 15:30 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +        Pageable pageable = PageRequest.of(0, USER_ACTIVITY_PER_PAGE);
넵넵~ 맞아요

2022-01-09 16:06 UTC, brainbackdoor requested changes
몇가지 피드백 남겨두었어요~ 확인해보고 궁금한 점 있으면 Comment 남겨주세요~

2022-01-09 16:06 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +        if (userActivity.getStatus() == ActivityStatus.FINISHED) {
이 로직이 반복되는데요. 중복을 없앨수는 없을까요?

2022-01-09 16:06 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse response = activityService.create(activityRequest);
mock 을 사용하셨군요! 그렇다면, 객체의 변화를 테스트에서 감지하지 못하지 않을까요?

2022-01-09 16:06 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +            .saveAll(Arrays.asList(userActivity, firstUserActivity, secondUserActivity));
given 절에서 무슨 일을 하는지 가독성이 너무 떨어지는데요. 테스트코드도 리팩토링해보는건 어떨까요?
테스트 코드에서도 객체지향 생활체조의 원칙을 지켜보려고 노력하는건 어떨까요

2022-01-11 02:04 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +        Pageable pageable = PageRequest.of(0, USER_ACTIVITY_PER_PAGE);
@Query(value = "SELECT DISTINCT a FROM UserActivity a LEFT JOIN FETCH a.activity LEFT JOIN FETCH a.user u WHERE u.id=:id AND a.id>=?1 ORDER BY a.createdAt DESC",
        countQuery = "SELECT count(DISTINCT a) FROM UserActivity a")
    Page<UserActivity> findByUserId(Pageable pageable, Integer id);
의 쿼리로  작성하게 되면 

org.springframework.dao.InvalidDataAccessApiUsageException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available!; nested exception is java.lang.IllegalStateException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available! 오류가 발생하고 있습니다 😭pageable을 제대로 읽지 못하는 것 같은데 혹시 이 부분은 어떻게 해결해야 할까요?😭

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/user/domain/User.java
> +    }
userActivity의 상태가 ONGOING이 아닌 FINISHED의 상태로 변경이 되면 점수에 더해주고 점수에 따른 레벨 변화가 이루어지는 것으로  updateLevel함수를 이용하여 의미를 파악할 수 있도록 변경하였습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/controller/UserActivityController.java
> +    @GetMapping("/users/{id}")
userActivity 와 User는 다대일의 연관관계를 맺고 있고 사용자의 아이디를 이용해서 사용자와 연관된 userActivity를 목록으로 받아오는 것으로 User 하위에 userActivity가 존재하므로 users/{id}/user-activities로  api를 변경하였습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/controller/UserActivityController.java
> +            userActivityService.create(userActivityRequest), HttpStatus.OK);
해당부분 확인하여 변경하였습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/controller/UserActivityController.java
> +    @DeleteMapping("/user-activities/{id}/users/{userId}")
해당부분 중복부분을 확인하고 중복되지 않도록 /user-activities/{id}/users/{userId}로 변경하였습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/domain/UserActivity.java
> +            this.user.levelUp(requestedUserActivity.getActivity().getScore());
해당부분 userActivity에 연관관계의 activity의 score를 가져오도록 getScore 메소드를 만들어 주고 이를 이용하도록 
if (this.status != requestedUserActivity.getStatus()) {
            this.user.updateLevel(requestedUserActivity);
        }
의 형식으로 변경하였습니다! (updateLevel 메소드에서 userActivitiy의 finish여부를 확인하고 getScore메소드를 사용하도록 변경하였습니다!)

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +    private ActivityRepository activityRepository;
userActivity는 사용자와 액티비티 모두 연관관계를 가지고 있어 userActivity를 생성하기 위해서 activity, user 모두 필요하고 user의 updateLevel등의 메소드를 사용하기 위해서 직접 의존을 하게 되었습니다! 혹시 이부분을 의존하지 않도록 변경해야 할까요? 😭 😭

2022-01-11 02:04 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +        if (userActivity.getStatus() == ActivityStatus.FINISHED) {
해당 부분 userActivity의 finished메소드를 이용하여 중복을 제거하였습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse response = activityService.create(activityRequest);
해당 부분 service계층의 테스트로 다시 repository에서 변경된 데이터를 가져오지 않고 id를 이용하여 기존의 userAcitivity를 가져온 후 userActivity의 update메소드를 통해 변경된 userActivity를 이용해 UserActivityResponse로 받아오고 있어 변경하고자 하는 데이터로 변경된 userActivity의 데이터를 가져오는 것을 확인할 수 있었습니다!

2022-01-11 02:04 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/domain/UserActivityRepositoryTests.java
> +            .saveAll(Arrays.asList(userActivity, firstUserActivity, secondUserActivity));
테스트 코드를 리팩토링하여 중복되는 부분은 메소드를 빼주고 이름을 명확하게 하여 의도를 나타내도록 리팩토링 하였습니다!

2022-01-22 14:36 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/service/UserActivityServiceTests.java
> +    }
테스트코드에서 중복이 계속 생기는데요. 공통되는 Fixture 를 묶어서 상속하는건 어떨까요

2022-01-22 14:36 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +    private ActivityRepository activityRepository;
아니요 그렇지는 않아요. 다만 의존관계를 염두해두지 않으면 추후에 양방향 혹은 순환 참조가 생길 수 있으니, 고려하시라는 얘기를 드리고 싶었어요.

2022-01-22 14:41 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse response = activityService.create(activityRequest);
아, 제가 이야기한 것은 thenReturn객체 필드의 변화를 감지하지 못한다는 의미였어요. Mock을 쓸 경우의 대표적인 단점입니다.
순수한 객체지향을 추구하는 이들은 Fake 객체를 써야 한다고 주장하고 있고, 행위주도개발을 이끌었던 이들은 Mock 사용의 이점을 어필하곤 하는데요. 양 쪽의 주장을 확인해보시는 것도 좋을듯해요.

2022-01-22 14:47 UTC, brainbackdoor approved these changes
리뷰 요청 메일을 놓쳤네요. 제가 2~3일 내에도 리뷰를 하지 않으면 데일리 때 한번 언급해주셔요~
피드백 반영 하신 부분 확인했어요. 어떻게 성장하는 기분을 느끼시는지 모르겠네요 ㅎㅎ;
테스트코드 추상화는 다른 리팩토링을 하며 좀 더 진행할 필요가 있어보입니다. 그리고 ApplicationContext 를 재사용하기 위해서는 어떻게 하는게 좋을지 한번 고민해보셔요~

2022-01-23 14:30 UTC, merged

2022-01-24 10:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/useractivity/service/UserActivityService.java
> +    private ActivityRepository activityRepository;
넵!! 확인하였습니다!😃

2022-01-24 10:54 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/activity/service/ActivityServiceTests.java
> +        ActivityResponse response = activityService.create(activityRequest);
확인하였습니다!!😃

2022-01-24 10:55 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/service/UserActivityServiceTests.java
> +    }
해당 부분 확인하고 공통 Fixture를 묶어 상속하도록 하였습니다!