Refactor: UserActivityTest, Review 리팩토링 진행
projects-workshop/walkerholic pull request #4
Opened 2022-01-24 10:45 UTC by yunhalee05

UserActivityTest 및 Review 리팩토링을 진행하였습니다!

✔️ UserActivityTest의 중복 메소드(userActivity)를 새로운 BaseUserActivityTests 클래스로 옮겨주고 이를 UserActivityRepositoryTest와 UserActivityServiceTest가 상속하여 사용할 수 있도록 공통 Fixture 생성
✔️ Review의 create, update, delete 기능을 리팩토링 진행
(각각의 기능 리팩토링 중간에 commit 하는 것을 놓치게 되었습니다 😭 죄송합니다 😭)

이전 PR과 관련하여 추가로 몇가지 질문사항이 있습니다!

❓ 이전에 pageable을 전달하는 부분에서 offset쿼리가 나가게되어 비효율적인 쿼리를 수정하는 부분에서 
Query(value = "SELECT DISTINCT a FROM UserActivity a LEFT JOIN FETCH a.activity LEFT JOIN FETCH a.user u WHERE u.id=:id AND a.id>=?1 ORDER BY a.createdAt DESC",
    countQuery = "SELECT count(DISTINCT a) FROM UserActivity a")
Page<UserActivity> findByUserId(Pageable pageable, Integer id); 
의 쿼리로 작성하게 되면

org.springframework.dao.InvalidDataAccessApiUsageException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available!; nested exception is java.lang.IllegalStateException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available! 오류가 발생하고 있습니다 😭pageable을 제대로 읽지 못하는 것 같은데 혹시 이 부분은 어떻게 해결해야 할까요?😭

❓ Mock객체를 이용하여 작성한 테스트에서 생성된 mockBean의 ApplicationContext을 재사용을 하고 싶어 추가로 클래스를 생성하고 상속받아 테스트를 실행하는 방안을 생각해 보았는데, 이미 UserActivityServiceTest에서 Fixture 클래스인 BaseUserActivityTest를 상속받아 구현하기가 어려운데 이런 경우에는 Fixture와 mockBean 클래스를 어떻게 구성해야 할까요?😭 

❓ Fake vs Mock을 비교하였을 때 Mock객체가 협력객체에 의존적이고 어떻게 작동해야 하는지 명시해야하는 점에서 테스트 코드에서는 Fake객체의 사용이 대안이 될 수 있다고 생각하게 되었습니다! 만약 작성된 UserActivityServiceTest코드에서 Fake 객체를 사용하게 된다면 
  Before
    public void setUp() {
        userActivityService = new UserActivityService(FakeUserActivityRepository);
    }
와 같은 형식으로 작성하는 것이 맞을까요?

감사합니다!!🙌

2022-01-24 21:32 UTC, brainbackdoor requested changes
빠르게 리팩토링하셨군요. 몇가지 고민점이 보여 Request Changes 해요~
그리고 질문에 대한 제 생각을 아래 남겨놔요~

1. `findByUserId(Pageable pageable, @Param("name") Integer id);` 한번 해보시겠어요?
2. 피드백에도 남겼지만, 스스로 고민하는 과정이 필요합니다. 어떻게 추상화하는 것이 좋을지..
3. 넵넵 맞아요. 다만 setUp 메서드가 반드시 필요한가요?

2022-01-24 21:32 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/BaseUserActivityTests.java
> +    }
ㅎㅎ 2번쨰 질문에 제 생각을 바로 말씀드리기 보다는, 
어떻게 추상화하면 좋을지 직접 고민해보시는게 더 도움이 될거라 생각합니다.

2022-01-24 21:32 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/review/service/ReviewService.java
> +    private UserRepository userRepository;
UserActivity 때도 말씀드리긴 했는데요. User가 상당히 여러군데에 직접 의존하고 있군요.
Reviewer, ActivityUser 등과 같이 서브도메인을 두어 간접참조하도록 설계하는 것은 어떨까요

2022-01-24 21:32 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/review/dto/ReviewRequest.java
> +    }
이왕 롬복을 쓰신다면 `@NoArgsConstructor(access = AccessLevel.PRIVATE)` 를 활용하시는건 어떨까요

2022-01-26 07:57 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/BaseUserActivityTests.java
> +    }
해당부분을 중복되는 method를 static으로 뽑아내고, mockBean 객체를 클래스에 만들어서 상속받는 형식으로 구현하였습니다!😀

UserActivity와 Activity service layer 테스트 시에는 MockBean객체를 상속받아서 테스트를 작성하였고, 
ReviewServiceTest에서는 FakeRepository를 이용하여 테스트를 실행하도록 해보았습니다! FakeRepository를 적용시에는 setUp메소드를 작성하지 않고 ReviewService 선언시 적용되도록 하였습니다!

2022-01-26 07:57 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/review/service/ReviewService.java
> +    private UserRepository userRepository;
멘토님 😭 여기서 서브도메인이 이해가 잘 안되어서요 😭 여기서 User에 적용한다면 User-Review의 연관관계만을 갖고있는 UserReview 객체를 새로 생성하고 User-UserReview를 일대일 관계로 맺어주라는 말씀이실까요? 😭 여기서 User-UserActivity-Activity는 User-Activity관계가 다대다의 관계에서 UserActivity를 이용하여 User-UserActivity(일대다), UserActivity-Activity(다대일)의 관계로 풀어주고 추가 정보를 입력하였는데 여기서는 User-ActivityUser-UserActivity의 관계로 한번 더 풀어내는 것일까요?😭 아니면 간접참조라면 연관관계를 맺지 않고 id만을 저장하여 간접참조 하도록 변경하는 것일까요?😭

2022-01-26 07:57 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/review/dto/ReviewRequest.java
> +    }
해당부분확인하고 변경하였습니다!😃

추가적으로 멘토님께서 말씀해주신
    Query(value = "SELECT DISTINCT a FROM UserActivity a LEFT JOIN FETCH a.activity LEFT JOIN FETCH a.user u WHERE u.id=:name AND a.id>=?1 ORDER BY a.createdAt DESC",
        countQuery = "SELECT count(DISTINCT a) FROM UserActivity a")
    Page<UserActivity> findByUserId(Pageable pageable, @Param("name") Integer id);
으로도 적용해 보았으나 처음과 동일한 
org.springframework.dao.InvalidDataAccessApiUsageException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available!; nested exception is java.lang.IllegalStateException: Required name for ParameterBinding [name: null, position: 1, expression: null] not available! 오류가 발생하였습니다. 😭

2022-01-30 06:25 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/review/service/ReviewService.java
> +    private UserRepository userRepository;
<img width="912" alt="스크린샷 2022-01-30 오후 3 21 12" src="https://user-images.githubusercontent.com/29951288/151689098-e0d8b8d3-7cd8-4ac1-803c-377b1b0bcd58.png">

우선, User 가 대부분의 도메인과 의존성이 있어 결합도가 높습니다.
다만, 말씀주신 것처럼 UserActivity 의 경우 의존관계가 문제는 없어서 지난번 리뷰에선 approve 했었는데요.
Product, Review, User 는 순환참조가 발생하여, 다시 언급드린거에요.

User 와 다른 모든 도메인이 라이프사이클이 같은지 한번 고민해보시는게 좋을듯해요. 
가령, Product의 경우 생성되고 수정되고 삭제되는 사이클이 User 의 라이프사이클과 다른데, 직접 의존하여 결합도를 높이는 것이 어떤 이점이 있을지 한번 고민해보면 좋겠다는 생각에 피드백 남겼어요~ 물론 UserActivity 도 마찬가지입니다.
어느 정도까지 간접참조하는 것이 적당할지 스스로 생각해보시면 좋을듯해요.

2022-01-30 06:26 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/review/dto/ReviewRequest.java
> +    }
제가 설정파일이 없어서 프로젝트는 디버깅해드리기가 좀 어렵네요. 
스스로 해보시고 안되면, 이 이슈는 기존대로 수행하는게 좋을듯하네요.

2022-01-30 06:38 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/domain/FakeProductRepository.java
> +public class FakeProductRepository implements ProductRepository {
아, 이런, 각 서비스가 Repository 를 직접 의존하고 있어서 Fake 객체로 Repository 를 작성했군요.

2022-01-30 06:38 UTC, brainbackdoor commented on src/test/java/com/yunhalee/walkerholic/useractivity/BaseUserActivityTests.java
> +    }
음.. 각각 그렇게 구성했을 때 어떤 이점이 있는걸까요?

2022-01-30 06:39 UTC, brainbackdoor reviewed
질문주신 부분에 다시 Comment 남겨두었어요~
이번에 어떤 의도로 리팩토링하신지 좀 더 생각을 듣고 싶어요

2022-02-02 05:55 UTC, yunhalee05 commented on src/test/java/com/yunhalee/walkerholic/useractivity/BaseUserActivityTests.java
> +    }
이전에 Mock객체를 사용하였을 때 발생하였던 문제(Mock 비용 문제 해결을 위한 상속과 Repository계층과 Service계층의 공통 메서드 상속 중복)와 FakeRepository를 테스트 코드에 어떻게 적용할 것이가에 대한 두가지 문제를 모두 해결해 보고자 하여 두가지 방법을 모두 적용해 보았습니다! 현재 다시 모두 FakeRepository를 적용한 ServiceLayerTest를 진행하도록 변경하였습니다!

2022-02-02 05:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/review/service/ReviewService.java
> +    private UserRepository userRepository;
자세한 설명 감사합니다! 😃 🙌 설명해주신 자료를 보고 발생되는 해결을 위해 User 객체에서 불필요한 의존(Review, UserAcitivity)을 삭제하여 단방향 연관관계로 이루어지도록 반영하였습니다!  UserActivity의 경우 user객체에 score 속성을 넣어 UserActivity와의 불필요한 연관관계를 맺지 않도록 변경하였습니다! 감사합니다!!

2022-02-02 05:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/review/dto/ReviewRequest.java
> +    }
넵! 감사합니다 😭 !!

2022-02-15 18:49 UTC, brainbackdoor approved these changes
아, 이 리뷰요청도 꽤 지연되었군요. 미안합니다.
이제 전반적으로 깔끔하게 잘 작성하시네요~ 👍🏻 
보통 처음에 작성한 PR의 목적 외의 변경은 다른 브랜치에서 작업을 진행 후 별도의 PR로 요청합니다.
몇가지 간단한 피드백 남겨두었는데, 확인 해주세요.

2022-02-15 18:49 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/domain/FakeProductRepository.java
> +public class FakeProductRepository implements ProductRepository {
요건 이제 안쓰는 Fake 객체이지요?
보통 Jpa repository를 직접 의존하도록 stubbing 을 하진 않구요.
의존 관계를 끊도록 구성해요. 조금 구성이 복잡해져서 의존관계를 UML 로 그려둘게요~
기존 서비스에서 ProductRepository를 의존하는건 동일하구요.
단지, ProductRepository가 직접 JpaRepository 를 의존하는 것이 아니라 어댑터를 두는 것이 달라집니다.
여기서는 ProductInfraRepository 라는 클래스가 JpaRepository를 의존하고 있는 ProductJpaRepository 를 구성하고 있는 형태입니다.

```java
    interface ProductRepository {
        void save(Product product);
    }

    static final class ProductInfraRepository implements ProductRepository {

        private final ProductJpaRepository productRepository;

        ProductInfraRepository(ProductJpaRepository productRepository) {
            this.productRepository = productRepository;
        }

        @Override
        public void save(Product product) {
            productRepository.save(product);
        }
    }

    interface ProductJpaRepository extends JpaRepository {}
```

```java
    static final class ProductStub implements ProductRepository {
        @Override
        public void save(Product product) {
            System.out.println("Save!");
        }
    }
```

<img width="640" alt="스크린샷 2022-02-16 오전 3 20 07" src="https://user-images.githubusercontent.com/29951288/154125220-ab32e808-74d7-43d9-af6c-a6c00c71302d.png">

2022-02-15 18:49 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/domain/Product.java
> +        this.average = (float) (Math.round(sum / (long) (size) * 100) / 100.0);
금액 등은 정확한 값을 요하는 경우엔 BigDecimal을 활용하는 것은 어떨까요

2022-02-16 11:07 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/follow/service/FollowService.java
> +            .collect(Collectors.toList());
해당부분 확인하여 로직을 분리하도록 적용하였습니다!

2022-02-16 11:11 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/domain/FakeProductRepository.java
> +public class FakeProductRepository implements ProductRepository {
네  맞습니다! 😀 해당부분 확인하였습니다! JPA를 사용하면서 Fake 이용하려고 할 때 코드가 복잡해져서 어떻게 사용해야 하는지 궁금했는데 자세히 설명해주셔서 감사합니다!! 😭

2022-02-16 11:11 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/domain/Product.java
> +        this.average = (float) (Math.round(sum / (long) (size) * 100) / 100.0);
해당부분 확인하여 BigDecimal을 이용하도록 변경하였습니다!! 감사합니다!🙌

2022-02-16 23:45 UTC, merged