Refactor: Product 리팩토링
projects-workshop/walkerholic pull request #6
Opened 2022-02-25 15:13 UTC by yunhalee05

Product 객체를 리팩토링 진행하였습니다!

✔️ 이전 PR에서 받은 Post의 부분 수정(findBy 메서드 재사용 및 피드백 적용)
✔️ Product 객체의 Controller, Servcie 리팩토링
✔️ Product의 ProductImages 일급컬렉션을 사용
✔️ Product의 Review와의 양방향 연관관계를 단방향으로 적용하고 ReviewInfo 객체를 만들고 사용하여 average값 구하도록 변경
✔️ ProductService의 각 메서드에 따른 Response를 만들고 재사용하도록 변경
✔️ product save 메서드를 create, update메서드로 나누어 의도를 명확히 하도록 변경

감사합니다!! 😀 🙌

2022-03-01 08:06 UTC, brainbackdoor requested changes
몇가지 피드백 남겨두었는데요. 확인해보시고 궁금한 점 있으면 메시지 주세요~ 🙏🏻

2022-03-01 08:06 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
> +        Optional.ofNullable(multipartFiles).orElseGet(Collections::emptyList)
MultipartFile 요청 값에 대한 유효성은 Controller에서 처리하는 것은 어떨까요?
`@RequestPart`에 대해 Bean Validation 으로는 체크하는 것은 어떤가요

2022-03-01 08:06 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
>      }
이미지를 처리하는 별도의 도메인 혹은 서비스를 도출하는 건 어떤가요

2022-03-01 08:06 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
> +        Pageable pageable = pageable(page, sort);
page와 관련된 별도의 class 를 작성하는 것은 어떤가요

2022-03-01 08:06 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
> +        if (category == null || category.isBlank()) {
이것도 마찬가지입니다. 요청 값에 대한 유효성 검증은 Controller 에서 하는 것이 어떨까요

2022-03-02 11:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/controller/ProductController.java
> +    @PatchMapping("/products")
patch는 데이터의 부분 수정시 사용되며 식별자가 없는 경우에는 예외를 발생시키고 post는 식별자가 존재하지 않으면 새 리소스를 생성하고 반환하는 것으로 데이터 생성시 사용된다는 것을 학습하였습니다! 해당부분을 확인하고 식별자를 pathVariable로 인지할 수 있도록 변경하였습니다!

2022-03-02 11:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/controller/ProductController.java
> +    @GetMapping("/users/{id}/products")
Products는 User가 삭제될 때 함께 제거 되므로 cascade 설정을 넣도록 수정하였습니다!

2022-03-02 11:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/controller/ProductController.java
> +    @GetMapping("/products/list")
해당부분 확인하고 동일한 부분을 반환하는 것으로 확인하여 중복되는 부분을 제거하고 기존 부분을 활용하도록 변경하였습니다!

2022-03-02 11:54 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/domain/Product.java
> +//    private List<ProductImage> productImages = new ArrayList<>();
확인하고 변경하였습니다! 😭

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/domain/Product.java
> +        Integer stock, Float price, User user) {
해당 부분 확인하고 price 값을 Bigdecimal로 변경하였습니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/domain/Product.java
> +        this.reviewInfo = new ReviewInfo();
ProductInfo로 추상화하고 user에서 product정보를 조회하지 않으므로 불필요한 참조를 삭제하도록 하였습니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/dto/ProductRequest.java
> +    public ProductRequest(String name, String description, String brand, String category, Integer stock, Float price, Integer userId) {
해당부분 확인하고 기본 생성자를 생성하였습니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/dto/ProductResponse.java
> +//    }
확인하고 변경하였습니다! 😭 죄송합니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
>      }
해당 부분을 ProductImageService 로 도출하도록 변경하였습니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
> +        Pageable pageable = pageable(page, sort);
해당부분을 확인하고 ProductSearchRequest 클래스로 작성하였습니다!

2022-03-02 11:55 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/service/ProductService.java
> +        if (category == null || category.isBlank()) {
해당부분 확인하고 controller에서 유효성 검증이 적용되도록 변경하였습니다! 감사합니다!

2022-03-02 12:50 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/product/controller/ProductController.java
> +    @PatchMapping("/products")
데이터 부분 수정이란 어떤 의미이신가요? 모든 update는 patch로 요청해야 하는걸까요?

2022-03-07 14:47 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/controller/ProductController.java
> +    @PatchMapping("/products")
put의 경우 넘어오지 않은 값은 null로 자원의 전체교체가 이루어지는 반면 patch는 넘어오지 않은 값은 기존의 값을 그대로 부분 교체가 이루어지는 것을 데이터 부분 수정이라 하게 되었습니다! 이 업데이트의 경우 새로운 객체를 생성하는 것이 아닌 기존의 정보를 부분 수정하는 것이기에 의도를 명확히 해야하기 위해서 patch를 사용하게 되었습니다!

2022-03-07 14:48 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/productImage/service/ProductImageService.java
> +            try {
해당부분을 확인하여 s3ImageUploader가 상품 이미지 업로드 기능을 완료한뒤 생성된 정보를 담은 productImage 객체를 반환하도록 변경하여 ProductImageService는 업로드된 정보의 이미지를 저장하고 상품에 이미지를 추가해주는 역할에 집중하도록 하였습니다!

2022-03-07 14:48 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/productImage/service/ProductImageService.java
> +                String fileName = deletedImage.substring(bucketUrl.length() + 1);
이 부분은 s3ImageUploader에서 fileName(기본 url(bucketUrl)을 제외한 부분)을 이용하여 해당 이미지를 삭제하기 위하여 substring을 이용하게 되었습니다! ( 해당부분은 s3ImageUploader의 deleteByFilePath메소드에서 처리하도록 하여 productImageService에서 불필요한 정보(bucketUrl)등을 사용하지 않도록 변경하였습니다! )

2022-03-07 14:48 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/product/dto/ProductSearchRequest.java
> +public class ProductSearchRequest {
해당부분을 확인하고 공통으로 사용되는 page, sort정보만을 담은 pageSortRequest로 변경하여 적용하였습니다!

2022-03-20 23:37 UTC, brainbackdoor approved these changes
이번 PR이 꽤 오래되었군요. 여기서 머지할게요.
Comment 남긴 것들 확인해보셔요~

2022-03-20 23:37 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +            String fileName = imageUrl.substring(bucketUrl.length() + uploadDir.length() + 2);
2 는 어떤 의미인가요?

2022-03-20 23:37 UTC, brainbackdoor commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +        return null;
null 을 리턴하는 이유가 있나요? 
ull을 리턴하기보다 빈객체 혹은  Optional을 활용하는 것은 어떨까요

https://www.slideshare.net/gyumee/null-142590829
http://www.mimul.com/pebble/default/2015/11/11/1447231720346.html

2022-03-22 09:48 UTC, merged

2022-03-24 12:14 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +            String fileName = imageUrl.substring(bucketUrl.length() + uploadDir.length() + 2);
이미지 URL의 '/' 이부분을 포함하는 만큼의 길이를 빼내기 위해 2를 사용하게 되었습니다!

2022-03-24 12:14 UTC, yunhalee05 commented on src/main/java/com/yunhalee/walkerholic/common/service/S3ImageUploader.java
> +        return null;
해당 부분 확인하여 null을 반환하지 않도록 imageURl을 반환하는 uploadImage 메서드로 수정하였습니다!